name = "followup"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "KV"
id = "ea5db34d2110466fa2d763011c07f36d"
preview_id = "ea5db34d2110466fa2d763011c07f36d"
